version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: ${APP_OS_VERSION}
        volumes:
            - ..:/workspace:cached
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - web
        command: sleep infinity

    web:
        image: nginx:${NGINX_VERSION}
        volumes:
            - "../etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../web:/var/www/html"
            - "../etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${NGINX_HTTP_PORT}:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - db
            - php
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "../etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../web:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin:${PMA_VERSION}
        ports:
            - "${PMA_HTTP_PORT}:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        restart: always
        depends_on:
            - db

    db:
        image: mariadb:${MARIADB_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_ROOT_HOST=%
            - MARIADB_AUTO_UPGRADE=1
        ports:
            - "${MARIADB_PORT}:3306"
        volumes:
            - "../data/db/data:/var/lib/mysql"
            - "../data/db/conf.d:/etc/mysql/conf.d"
    eggdrop:
        image: eggdrop:${EGG_VERSION:-latest}
        container_name: eggdrop
        env_file:
            - ".env"
        environment: 
            - SERVER=${EGG_SERVER}
            - NICK=${EGG_NICK}
### Make this match your listen setting in the config
        ports:
            - "3333:3333"
        depends_on:
            - db
### Change this to the path with your config and user/channel files
        volumes:
            - ../data/eggdrop/data:/home/eggdrop/eggdrop/data/
            - ../IMC.tcl:/home/eggdrop/eggdrop/scripts2/IMC.tcl
        command: IMC.conf
        stdin_open: true
        tty: true
        restart: always
